name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: redis, pdo_mysql
        coverage: none

    - name: Copy .env
      run: |
        cp .env.example .env
        sed -i'' -e 's/^DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
        sed -i'' -e 's/^DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i'' -e 's/^DB_PORT=.*/DB_PORT=3306/' .env
        sed -i'' -e 's/^DB_DATABASE=.*/DB_DATABASE=laravel/' .env
        sed -i'' -e 's/^DB_USERNAME=.*/DB_USERNAME=root/' .env
        sed -i'' -e 's/^DB_PASSWORD=.*/DB_PASSWORD=password/' .env
        sed -i'' -e 's/^QUEUE_CONNECTION=.*/QUEUE_CONNECTION=redis/' .env
        sed -i'' -e 's/^REDIS_HOST=.*/REDIS_HOST=127.0.0.1/' .env
